[package]
name = "aoc2021"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ex = "0.1"
http_req = {version="0.8",features=["rust-tls"],default-features=false}
